config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get :index_json
    end
  end

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'
  get 'sessions/logout' => 'sessions#destroy'

  get 'chatroom/' => 'chats#chatroom'
  post 'sendtorobot/' => 'messages#sendtorobot'
  post 'createarticle/' => 'articles#create'
  resources :articles, :only => [:destroy, :show]
  resources :footsteps, :only => [:create]
  post 'updatelike/' => 'articles#update'
  get 'developlog/' => 'developlog#index'

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user,optional: true
  belongs_to :friend, :class_name => "User",optional: true
  mount_uploader :picture, PictureUploader
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SessionsHelper
  include ChatsHelper
	def create
 		if params[:article][:content] == "" && params[:article][:picture].nil?
			redirect_to chats_path, flash: {"error": "还没有写心情呢"}
			return
		end
 		article = Article.new(get_params)
		if article.save!
			redirect_to chats_path, flash: {"success": "发送成功"}
		else
			redirect_to chats_path, flash: {"warning": "发送失败"}
		end
	end

	def destroy
		article = Article.find_by_id(params[:id])
		article.destroy
		redirect_to chats_path, flash: {"success": "刪除成功"}
	end

	def show
		if params[:id].to_s == current_user.id.to_s
			redirect_to chats_path
			return
		end
    @friends=current_user.friends+current_user.inverse_friends
    @userinfo = User.find_by_id(params[:id])
    @onlineusers = @userinfo.friends+@userinfo.inverse_friends-[current_user]-current_user.friends-current_user.inverse_friends
    @selfarticle = @userinfo.articles
    @currentallchat = current_user.chats
    @onlinefriends = @friends-[@userinfo]-(User.all-@userinfo.friends-@userinfo.inverse_friends)
    @newfootstep = Footstep.new
    @footstepall = @userinfo.footsteps
	end

	def update
		art = Article.find_by_id(params[:id])
		cnt = art[:like] + 1;
		art.update_attributes(like: cnt)
		respond_to do |format|
			format.json {render json: {success: cnt}}
		end
	end

	def get_params
		params[:article][:user_id] = params[:user_id]
		params.require(:article).permit(:user_id, :content, :picture)
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articlelist.html.erb
<div class="card card-cascade narrower <% if current_user.id == @userinfo.id %>mt-5<% end %>" id="timeline" style="background-color: rgb(0,0,0,.4);">
  <div class="view view-cascade gradient-card-header narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center" style="background-color: rgb(54, 100, 139);">
    <a href="" class="white-text mx-3">
      <% if current_user.id == @userinfo.id %>
      我的动态
      <% else %>
      Ta的动态
      <% end %>
    </a>
    <div>
      <% if current_user.id == @userinfo.id %>
      <a href="/chats/#timeline" type="button" class="btn btn-secondary py-2 px-4">更新</a>
      <% else %>
      <a href="/articles/<%= @userinfo.id %>/#timeline" type="button" class="btn btn-secondary py-2 px-4">更新</a>
      <% end %>
      <%#= link_to chats_path, type: "button", class: "btn btn-success py-2 px-4" do %>
      <!-- 刷新 -->
      <%# end %>
    </div>
  </div>

  <div class="p-4 pb-5">
    <% if @selfarticle.count == 0 %>
      <p class="px-4 card-text text-center">
        Ta真的好懒，没有任何动态
      </p>
    <% end %>
    <% @selfarticle.each do |article| %>
      <hr class="my-0">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">

        <% if article.user.picture? %>
          <%= image_tag article.user.picture.url, class: "img-sm" %>
        <% else %>
           <%= image_tag "user-icon.png", class: "img-sm" %>
        <% end %>

          </div>
          <div class="col-md-6 pl-0">
            <h5 class="card-title text-muted">
              <% if current_user.id == @userinfo.id %>
              我
              <% else %>
              <%= @userinfo.name %>
              <% end %>
            </h5>
              <%= %>
            <p class="card-text">
              于<%= article.created_at.to_s %>&nbsp;&nbsp;分享：
            </p>
          </div>
          <div class="col-md-4 text-right">
            <button type="button" class="btn btn-sm green px-2 py-1 mt-3 ilikeit"><i class="fa fa-thumbs-o-up">&nbsp;&nbsp;<span class="likenumber"><%= article.like %></span><div style="display: none"><%= article.id %></div></i></button>
            <% if current_user.id == article.user.id %>
            <%= link_to article_path(article.id), method: :delete, class: ""  do %>
            <button type="button" class="btn btn-sm red px-2 py-1 mt-3"><i class="fa fa-times"></i></button>
            <% end %>
            <% end %>
          </div>
        </div>
        <p class="card-text mt-2">
          <%= article.content %>
          <% if article.picture? %>
          <%= image_tag article.picture.url, style: "width:100%", class: "mt-3" %>
          <% end %>
        </p>
      </div>
    <% end %>
    <script type="text/javascript">
      $(".ilikeit").on("click", function(){
        ele = $(this);
        $.ajax({
          type: 'POST',
          url: '/updatelike',
          dataType: 'JSON',
          data: {
            "id" : $(this).find("div").html()
          },
          success: function(data){
            ele.children("i").children("span.likenumber").html(data.success)
          },
          error: function(data){
          }
        })
      })
    </script>
  </div>

</div>

app/views/articles/_friendsarticlelist.html.erb
<div class="card card-cascade narrower mt-5" id="friendstate" style="background-color: rgb(0,0,0,.4);">
  <div class="view view-cascade gradient-card-header cyan narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
    <a href="" class="white-text mx-3">好友动态</a>
    <div>
      <a href="/chats/#friendstate" class="btn btn-secondary py-2 px-4" type="button">更新</a>
      <%#= link_to chats_path, type: "button", class: "btn btn-success py-2 px-4" do %>
      <!-- 刷新 -->
      <%# end %>
    </div>
  </div>

  <div class="p-4 pb-5">
    <% if @friendsarticle.count == 0 %>
      <p class="px-4 card-text text-center text-muted">
        Ta们真的好懒，没有任何动态
      </p>
    <% end %>
    <% @friendsarticle.each do |article| %>
      <hr class="my-0">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <a href="/articles/<%= article.user.id %>">

        <% if article.user.picture? %>
          <%= image_tag article.user.picture.url, class: "img-sm" %>
        <% else %>
           <%= image_tag "user-icon.png", class: "img-sm" %>
        <% end %>

            </a>
          </div>
          <div class="col-md-8 pl-0">
            <h5 class="card-title text-muted">
              <%= article.user.name %>
            </h5>
              <%= %>
            <p class="card-text">
              于<%= article.created_at.to_s %>&nbsp;&nbsp;分享了：
            </p>
          </div>
          <div class="col-md-2 text-right">
            <button type="button" class="btn btn-sm blue px-2 py-1 mt-3 ilikefiendarticle"><i class="fa fa-thumbs-up">&nbsp;&nbsp;<span class="friendarticlelikenumber"><%= article.like %></span><div style="display: none"><%= article.id %></div></i></button>
          </div>
        </div>
        <p class="card-text mt-2">
          <%= article.content %>
          <% if article.picture? %>
          <%= image_tag article.picture.url, style: "width:100%", class: "mt-3" %>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>

</div>


<script type="text/javascript">
  $(".ilikefiendarticle").on("click", function(){
    ele = $(this);
    $.ajax({
      type: 'POST',
      url: '/updatelike',
      dataType: 'JSON',
      data: {
        "id" : $(this).find("div").html()
      },
      success: function(data){
        ele.children("i").children("span.friendarticlelikenumber").html(data.success)
      },
      error: function(data){
      }
    })
  })
</script>

app/views/articles/_new.html.erb
<div class="card card-cascade narrower mt-5" style="background-color: rgb(0,0,0,.4);">
  <div class="view view-cascade gradient-card-header lighten-2 narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center" style="background-color: rgb(255, 106, 106);">
    <a href="" class="white-text mx-3">发表动态</a>
    <div>
      <a href="/chats" type="button" class="btn btn-secondary py-2 px-4">重新编辑</a>
      <%#= link_to chats_path, type: "button", class: "btn btn-success py-2 px-4" do %>
      <!-- 刷新 -->
      <%# end %>
    </div>
  </div>

  <div class="px-4 pb-5">
    <%= form_for @newarticle, url: createarticle_path, method: :post do |f| %>
    <div class="row pr-4">
      <div class="col-md-12">

        <div class="md-form">
          <div class="file-field">
              <i class="fa fa-camera-retro float-left" style="font-size:40px;color:grey"> <%= f.file_field :picture %> </i>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text" placeholder="添加图片">
            </div>
          </div>
        </div>

        <div class="md-form mb-4 pink-textarea active-pink-textarea-2">
          <i class="fa fa-angle-double-right prefix" style="color:rgb(211,211,211,.6);"></i>
          <label for="post_body">分享你的生活...</label>
          <%= hidden_field_tag :user_id, current_user.id %>
          <%= f.text_area :content, class: "md-textarea form-control", rows: 3 %>
        </div>
      </div>
    </div>
    <div class="row pr-4">
      <div class="col-md-12 text-right">
        <%= f.submit '与朋友分享', class: 'btn btn-warning lighten-2 btn-sm' %>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/articles/show.html.erb
<body class="fixed-sn black-skin" aria-busy="true">
  
  <%= render 'chats/header' %>
  <main>
    <div class="container-fluid">
      <%= render 'chats/addfriend' %>

      <div class="row">
        <div class="col-md-6">
            <%= render 'users/selfinfo' %>
            <%= render 'footsteps/showfootstep' %>
            <%= render 'footsteps/newfootstep' %>


        </div>
        <div class="col-md-6">
            <%= render 'users/onlinefriend' %>
            <%= render 'users/onlineuser' %>
            <%= render 'articles/articlelist' %>

        </div>
      </div>

    </div>
    <%= render 'chats/messagetoastr' %>
  </main>

  <%= render 'layouts/footer' %>

</body>