config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get :index_json
    end
  end

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'
  get 'sessions/logout' => 'sessions#destroy'

  get 'chatroom/' => 'chats#chatroom'
  post 'sendtorobot/' => 'messages#sendtorobot'
  post 'createarticle/' => 'articles#create'
  resources :articles, :only => [:destroy, :show]
  resources :footsteps, :only => [:create]
  post 'updatelike/' => 'articles#update'
  get 'developlog/' => 'developlog#index'

end

app/models/chat.rb
class Chat < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :messages, :dependent => :destroy
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  include SessionsHelper
  include ChatsHelper
#   respond_to :js, :html
  before_action :logged_in
  before_action :set_chat, except: [:index, :new, :create, :chatroom]
  before_action :correct_user, only: :show

  def index
    @friends=current_user.friends+current_user.inverse_friends
    @user_form = current_user
    @onlineusers = User.all.where(online: 1)
    offlineusers = User.all.where(online: 0)
    @onlinefriends = @friends-offlineusers
    @onlineusers = @onlineusers-[current_user]-@friends
    @newarticle = Article.new
    @selfarticle = current_user.articles
    fa1 = Article.find_by_sql("select articles.*, users.name, users.email from users, friendships, articles where users.id = friendships.user_id and friendships.friend_id = articles.user_id and users.id = " + current_user.id.to_s);
    fa2 = Article.find_by_sql("select articles.*, users.name, users.email from users, friendships, articles where users.id = friendships.friend_id and friendships.user_id = articles.user_id and users.id = " + current_user.id.to_s);
    @friendsarticle = fa1+fa2
    @userinfo = current_user
    @currentallchat = current_user.chats
    @footstepall = @userinfo.footsteps
    robot = User.find_by(email: "robot@test.com")
    if robot.nil?
      robot = User.new(:name=> "robot", :email=> "robot@test.com", :online =>"1", :password=> "123456")
      #robot = User.new(:name=> "robot", :email=> "robot@test.com", :online =>"1", :password=> "123456", :picture => "/asserts/robot.jpg")
      if robot.save!
        flash= {success: "创建机器人成功"}
        redirect_to chats_path, flash: flash
      else
        flash= {danger: "创建机器人失败，请联系管理人员"}
        redirect_to root_path, flash: flash
      end
    end
  end

  def add_user
    if params[:users].nil?
      redirect_to chat_path(@chat), flash: {:info => "选择的用户组为空"}
    else
      params[:users].each do |id|
        @chat.users<<User.find_by_id(id)
      end
      redirect_to chat_path(@chat), flash: {:info => "用户已成功拉入群聊"}
    end
  end

  def delete_user
    user=User.find_by_id(params[:user_id])
    @chat.users.delete(user)
    if @chat.users.count == 1
      @chat.users.delete(@chat.users[0][:id])
    end
    redirect_to chat_path(@chat), flash: {:warning => "#{user.name}已成功退出群聊"}
  end

  def create
    user=User.find_by_id(params[:users])

    current_user.chats.each do |chat|
      if (chat.users-[user, current_user]).blank?
        redirect_to chat_path(chat) and return
      end
    end

    @chat = Chat.new
    @chat.users<<user
    @chat.users<<current_user
    @chat.admin_id=current_user.id
    @chat.name="#{user.name}-#{current_user.name}"
    Rails.logger.info(user)
    Rails.logger.info(current_user)
    Rails.logger.info("==============================")

    if @chat.save!
      redirect_to chat_path(@chat)
    else
      flash[:warning] = "错误,请重试"
      # redirect_to chats_path
      render 'chats/show'
    end
  end

  def update
    if @chat.update_attributes(chat_params)
      flash= {success: "修改成功"}
    else
      flash= {danger: "修改失败，请重试"}
    end
    redirect_to chat_path(@chat), flash: flash
  end

  def trans_auth
    @chat.update_attribute(:admin_id, params[:admin_id])
    redirect_to chat_path(@chat), flash: {success: '移交成功！'}
  end

  def destroy
    @chat.destroy
    redirect_to chatroom_path, flash: {:danger => '聊天已删除'}
  end

  def show
    @new_message = Message.new
    @users_in_chat= @chat.users-[current_user]
    @friends=current_user.friends+current_user.inverse_friends
    robot = User.find_by(email: "robot@test.com")
    @friends_out_chat=@friends-@chat.users-[robot]
    offlineusers = User.all.where(online: 0)
    @onchatuser = @chat.users-offlineusers
    @currentallchat = current_user.chats-[@chat]
  end

  def chatroom
    friends=current_user.friends+current_user.inverse_friends
    if friends.count == 0
      redirect_to chats_path, flash: {:danger => 'no friends'}
    else
      if current_user.chats.count == 0
        user=friends[0]
        @chat = Chat.new
        @chat.users<<user
        @chat.users<<current_user
        @chat.admin_id=current_user.id
        @chat.name="#{user.name}-#{current_user.name}"
        if @chat.save
          redirect_to chat_path(@chat)
        else
          flash[:warning] = "错误,请重试"
          redirect_to chats_path
        end
      else
        redirect_to chat_path(current_user.chats[0])
      end
    end
  end

  # private

  def chat_params
    params.require(:chat).permit(:name, :description)
  end

  def logged_in
    #logged_in = false
    unless logged_in?
      store_location
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  def set_chat
    @chat=Chat.find_by_id(params[:id])
    if @chat.nil?
      redirect_to chats_path, flash: {:warning => "没有找到此次聊天的信息"}
    end
  end

  def correct_user
    if @chat.users.include?(current_user)
    else
      redirect_to chatroom_path, flash: {warning: '聊天已删除'}
    end
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chatroommanage.html.erb
<div class="card card-cascade"  style="background-color: rgb(0,0,0,.4);">
  <div class="view view-cascade gradient-card-header lighten-2 p-2" style="background-color:rgb(205, 38, 38, .35);">
      <div class="row">
        <div class="col-md-12 pt-1 text-left" style="height: 42px;">
          <h3><b>聊天室详细信息</b></h3>
        </div>
        <div class="col-md-12 text-right">

        <% if current_user.id==@chat.admin_id %>
        <% if @chat.users[0][:email] == "robot@test.com" || @chat.users[1][:email] == "robot@test.com" %>
        <% else %>
        
        <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#chatroomadduser">
          邀请成员
        </button>
        <div class="modal fade" id="chatroomadduser" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">加入用户</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <%= form_for @chat, url: add_user_chat_path(@chat), method: :post, role: 'form' do |f| %>
              <div class="modal-body">

                <%= select_tag :users, options_for_select(@friends_out_chat.map { |user| [user.name, user.id] }), class: "mdb-select md-form colorful-select dropdown-default", multiple: "multiple", multiple: true, style: "width: 100%" %>

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                <%= f.submit '确定', class: 'btn btn-primary btn-sm' %>
              </div>
              <% end %>

            </div>
          </div>
        </div>

        <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#transroomadmin">
          转移权限
        </button>
        <div class="modal fade" id="transroomadmin" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">移交管理权限</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= form_for @chat, url: trans_auth_chat_path(@chat), method: :patch, role: 'form' do |f| %>
              <div class="modal-body">
                <%= select_tag :admin_id, options_for_select(@users_in_chat.map { |user| [user.name, user.id] }), class: "mdb-select md-form colorful-select dropdown-danger", style: "width: 100%" %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                <%= f.submit '确定', class: 'btn btn-primary btn-sm' %>
              </div>
              <% end %>

            </div>
          </div>
        </div>
        <% end %>


        <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#editroomname">
          修改聊天室名称
        </button>
        <div class="modal fade" id="editroomname" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">编辑房间名</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= form_for @chat, url: chat_path(@chat), method: :patch, role: "form" do |f| %>
              <div class="modal-body">

                <div class="md-form">
                  <%= f.text_field :name, class: "form-control" %>
                  <label for="name">填入新的房间名</label>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                <%= f.submit '确定', class: 'btn btn-primary btn-sm' %>
              </div>
              <% end %>

            </div>
          </div>
        </div>

        <% end %>

          <%= link_to delete_user_chat_path(user_id: current_user.id, id: @chat.id), method: :delete, class: 'btn btn-danger btn-sm' do %>
              退出房间
          <% end %>
        </div>
      </div>
    <!-- </h4> -->
  </div>
  <div class="card-body">
    <p class="card-text pt-2">
      房间名: <%= @chat.name %>
    </p>
    <hr>
    <p class="card-text">
      在线用户:<br>
      <div class="row custom-scrollbar scrollbar-near-moon" style="height: 215px; max-height: 215px; overflow-y: auto;">
        <% @onchatuser.each do |user| %>
          <div class="col-md-3">
            <div class="card card-cascade" style="width: 100px; height: 140px">
              <div class="view view-cascade overlay">
        <% if user.name == "robot"%>
          <%= image_tag "robot.jpg", class: "card-img-top", style: "height: 100px; width: 100px", alt: "normal" %>
        <% else %>
          <% if user.picture? %>
            <%= image_tag user.picture.url, class: "card-img-top", style: "height: 100px; width: 100px", alt: "normal" %>
          <% else %>
             <%= image_tag "user-icon.png", class: "card-img-top", style: "height: 100px; width: 100px", alt: "normal" %>
          <% end %>
        <% end %>

                <% if current_user.id==@chat.admin_id %>
                <% if current_user.id!=user.id %>
                <%= link_to delete_user_chat_path(user_id: user.id, id: @chat.id), method: :delete, class: 'm-0 mb-2', style:'color:red;position:absolute;top:0%;right:0%' do %>
                <i class="fa fa-remove"></i>
                <% end %>
                <% end %>
                <% end %>
                <a href="/articles/<%= user.id %>"><div class="mask rgba-white-slight"></div></a>
              </div>
              <div class="card-body card-body-cascade text-center text-muted p-0 pt-2"  style="height: 40px; overflow: hidden;">
                <%= truncate(user.name,length: 11) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </p>
    <hr>
    <p class="card-text">
    所有用户:<br>
    <div class="row custom-scrollbar scrollbar-near-moon" style="height: 215px; max-height: 215px; overflow-y: auto;">
    <% @chat.users.each do |user| %>
      <div class="col-md-3">
        <div class="card card-cascade" style="width: 100px; height: 140px">
          <div class="view view-cascade overlay">

            <% if user.name == "robot"%>
              <%= image_tag "robot.jpg", class: "card-img-top", style: "height: 100px; width: 100px", alt: "normal" %>
            <% else %>
              <% if user.picture? %>
                <%= image_tag user.picture.url, class: "card-img-top", style: "height: 100px; width: 100px", alt: "normal" %>
              <% else %>
                 <%= image_tag "user-icon.png", class: "card-img-top", style: "height: 100px; width: 100px", alt: "normal" %>
              <% end %>
            <% end %>


            <% if current_user.id==@chat.admin_id %>
            <% if current_user.id!=user.id %>
            <%= link_to delete_user_chat_path(user_id: user.id, id: @chat.id), method: :delete, class: 'm-0 mb-2', style:'color:red;position:absolute;top:0%;right:0%' do %>
            <i class="fa fa-remove"></i>
            <% end %>
            <% end %>
            <% end %>
            <a href="/articles/<%= user.id %>"><div class="mask rgba-white-slight"></div></a>
          </div>
          <div class="card-body card-body-cascade text-center text-muted p-0 pt-2" style="height: 40px; overflow: hidden;">
            <%= truncate(user.name,length: 11) %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
    </p>
  </div>
</div>

app/views/chats/_chatwindow.html.erb
<div class="card card-cascade"  style="background-color: rgb(0,0,0,.4);">
  <div class="view view-cascade gradient-card-header p-2" style="background-color:rgb(0, 0, 128, 0.2);">

    <div class="row">
        <div class="col-md-12">
            <h2 class="card-header-title mb-0 text-left ml-3 align-items-center mt-1" style="height: 38px; overflow: hidden;">
              <%= truncate(@chat.name, length: 20) %>
              <%# if @chat.users[0][:id] == current_user[:id] %>
              <%#= truncate(@chat.users[1][:name], length: 10) %>
              <%# else %>
              <%#= truncate(@chat.users[0][:name], length: 10) %>
              <%# end %>
              </h2>
        </div>
        <div class="col-md-12 text-right">
          <% if current_user.id==@chat.admin_id %>
            <%= link_to destroyall_messages_path(chat_room: @chat.id), method: :delete, class: 'btn btn-warning btn-sm' do %>
              清空窗口
            <% end %>

            <%= link_to chat_path(@chat), method: :delete, class: 'btn btn-danger btn-sm' do %>
              删除聊天
            <% end %>

          <% else %>
            <%= link_to delete_user_chat_path(user_id: current_user.id, id: @chat.id), method: :delete, class: 'btn btn-danger btn-sm' do %>
              退出聊天
            <% end %>
          <% end %>

        </div>
    </div>

  </div>

  <div class="card-body card-body-cascade" >
    <div class="card-text custom-scrollbar scrollbar-near-moon">

        <div id="demo-chat-body">
          <%= render 'chats/chatwindowbody' %>
        </div>

    </div>

    <hr>
    <%#= form_for @new_message, remote: true, id: "msgForm" do |f| %>
      <%#= hidden_field_tag :chat_room, @chat.id %>
      <input type="hidden" name="chat_room" id="chat_room" value="<%= @chat.id %>">
      <input type="hidden" name="chat_first_user" id="chat_first_user" value="<%= @chat.users[0][:email] %>">
      <input type="hidden" name="chat_second_user" id="chat_second_user" value="<%= @chat.users[1][:email] %>">
      <% if current_user.picture? %>
        <% picture = current_user.picture.url %>
      <% else %>
        <% picture = "user-icon.png" %>
      <% end %>
      <input type="hidden" name="chat_picture" id="chat_picture" value="<%= picture %>">
      <!-- <input class="form-control" placeholder="说点什么..." type="text" name="message[body]" id="message_body"/> -->
        <div class="md-form amber-textarea active-amber-textarea mb-0">
          <i class="fa fa-edit prefix" style="color:rgb(211,211,211,.6);" ></i>
          <textarea type="text" id="message_body" name="message[body]" class="md-textarea form-control" rows="3"></textarea>
          <label for="message_body">说点什么...</label>
        </div>
      <%#= f.text_field :body, class: "form-control", placeholder: "Type your message here..."%>
        <%#= f.button "Send", class: "btn btn-md btn-secondary m-0 px-3" %>
        <div class="row">
        <div class="col-md-8 pr-0">
          <a class="emojiji"> 😂 </a>
          <a class="emojiji"> 😆 </a>
          <a class="emojiji"> 😉 </a>
          <a class="emojiji"> 🙂 </a>
          <a class="emojiji"> 🙃 </a>
          <a class="emojiji"> 😎 </a>
          <a class="emojiji"> 😍 </a>
          <a class="emojiji"> 😘 </a>
          <a class="emojiji"> 😅 </a>
          <a class="emojiji"> 👿 </a>
          <a class="emojiji"> 👌 </a>
          <a class="emojiji"> ✌ </a>
          <a class="emojiji"> 👍 </a>
          <a class="emojiji"> 👎 </a>
          <a class="emojiji"> ✊ </a>
          <a class="emojiji"> 👊 </a>
          <a class="emojiji"> 👏 </a>
          <a class="emojiji"> 💪 </a>
          <a class="emojiji"> 👦 </a>
          <a class="emojiji"> 👧 </a>
          <a class="emojiji"> 🍦 </a>
          <a class="emojiji"> 🍧 </a>
          <a class="emojiji"> 🍨 </a>
          <a class="emojiji"> 🚓 </a>
          <a class="emojiji"> 🚔 </a>
          <a class="emojiji"> 🚕 </a>
          <a class="emojiji"> 🚖 </a>
          <a class="emojiji"> 🚗 </a>
          <a class="emojiji"> 🚘 </a>
          <a class="emojiji"> 🚚 </a>
          <a class="emojiji"> 🚛 </a>
          <a class="emojiji"> 🍎 </a>
          <a class="emojiji"> 🍏 </a>
          <a class="emojiji"> 🍐 </a>
          <a class="emojiji"> 🍑 </a>
          <a class="emojiji"> 🍒 </a>
          <a class="emojiji"> 🍓 </a>
          <a class="emojiji"> 🍅 </a>
          <a class="emojiji"> 🍆 </a>
          <a class="emojiji"> 🌽 </a>
          <a class="emojiji"> 🍄 </a>
          <a class="emojiji"> 🌰 </a>
          <a class="emojiji"> 🍞 </a>
          <a class="emojiji"> 🍖 </a>
        </div>
        <script type="text/javascript">
            $(document).ready(
                function(){
                    document.onkeydown = function()
                    {
                        var oEvent = window.event;
                        if (oEvent.keyCode == 13 && oEvent.ctrlKey) {
                            // alert("你按下了ctrl+enter");
                            mes_send();
                        }
                    }
                }
            );
            $(".emojiji").on('click', function(){
            tmp = $("#message_body").val();
            $("#message_body").val(tmp+$(this).html());
          })
        </script>
        <div class="col-md-4 text-right">
          <button class="btn btn-warning radius m-0 px-3 py-2" type="button" id="msgClear">清空</button>
          <button class="btn btn-success radius ml-3 px-3 py-2" type="button" id="msgSendBtn">发送</button>
        </div>
        </div>
    <%# end %>

  </div>

</div>
        

<script>
    var $cont = $('.nano-content');
    $cont[0].scrollTop = $cont[0].scrollHeight;
</script>

<script type="text/javascript">
    function mes_send(){
        if ($("#message_body").val() == ""){
            alert("输入为空")
            return
        }

        // if ($("#chat_first_user").val() == "robot@test.com" || $("#chat_second_user").val() == "robot@test.com" ){
        if($("#chat_first_user").val().indexOf("robot")!=-1||$("#chat_second_user").val().indexOf("robot")!=-1 ){//不等于-1 证明是存在这个的 是机器人
            bodymsg = $("#message_body").val();
            targeturl = "http://openapi.tuling123.com/openapi/api/v2";
            $.ajax({
                type: 'POST',
                url: '/sendtorobot',
                dataType: 'JSON',
                data: {
                    "body": bodymsg,
                    "targeturl": targeturl,
                    "chat_room": $("#chat_room").val()
                },
                success: function(data){
                    var now = new Date();
                    var year = now.getFullYear(); //得到年份
                    var month = now.getMonth()+1;//得到月份
                    var date = now.getDate();//得到日期
                    var day = now.getDay();//得到周几
                    var hour = now.getHours();//得到小时
                    var minu = now.getMinutes();//得到分钟
                    var sec = now.getSeconds();//得到秒
                    mytime = year + "-" + month + "-" + date+ " " + hour + ":" + minu + ":" + sec
                    $("#message_body").val("");

                    var str1='<li class="mar-btm">\n' +
                        '  <div class="media-right">\n' +
                        '\n' +
                        '\n' +
                        '    <img class="img-sm" src="<%= picture %>">\n' +
                         // '    <img class="img-sm" src="/assets/robot.jpg">\n' +

                        '\n' +
                        '  </div>\n' +
                        '  <div class="media-body pad-hor speech-right">\n' +
                        '    <div class="speech">\n' +
                        '      <p class="media-heading">我\n' +
                        '        <text class="speech-time">\n' +
                        '          <i class="fa fa-clock-o fa-fw"></i>\n' +
                        mytime +
                        '        </text>\n' +
                        '      </p>\n' +
                        '      <p style="margin-bottom: 5px; margin-top: 5px;">'+ bodymsg+'</p>\n' +
                        '    </div>\n' +
                        '  </div>\n' +
                        '</li>'
                    var str2 ='<li class="mar-btm">\n' +
                        '  <div class="media-left">\n' +
                        '\n' +
                        '\n' +
                        // '    <img class="img-sm" src="/assets/user-icon-6122bab3bf45f283f96860b90f4e0846a25f9e68927904222c21e8d2ca26d79f.png">\n' +
                        '    <img class="img-sm" src="/assets/robot.jpg">\n' +
                        '\n' +
                        '  </div>\n' +
                        '  <div class="media-body pad-hor ">'+
                        '<div class="speech">\n' +
                        '      <p class="media-heading">robot@test.com\n' +
                        '        <text class="speech-time">\n' +
                        '          <i class="fa fa-clock-o fa-fw"></i>\n' +
                        mytime +
                        '        </text>\n' +
                        '      </p>\n' +
                        '      <p style="margin-bottom: 5px; margin-top: 5px;">'+data["ret_msg"]+'</p>\n' +
                        '    </div>'
                    // $(".list-unstyled")[0].append("<p>Hello</p>")
                    $(".list-unstyled").append(str1)
                    $(".list-unstyled").append(str2)
                    document.getElementsByClassName("nano-content pad-all")[0].scrollTop= document.getElementsByClassName("nano-content pad-all")[0].scrollHeight
                },
                error: function(data){
                    $("#message_body").val("");
                }
            })
        }
        else{
            // alert("发送成功!")
            // location.reload();
            var msgdata = {
                "controller": "messages",
                "action": "create",
                "message" : {
                    "body" : $("#message_body").val()
                },
                "chat_room" : $("#chat_room").val()
            }
            $.ajax({
                type: 'POST',
                url: '/messages',
                dataType: "JSON",
                data: msgdata,
                success: function(data){
                    // alert("succeed 1")
                    // alert(data.success)
                    if(data.success == "1"){//发送失败的话 success 是1 这里是写一个警告框
                        // alert("failed 2")
                        toastr.options = {
                            "closeButton": true,
                            "debug": false,
                            "newestOnTop": false,
                            "progressBar": true,
                            "positionClass": "toast-bottom-left",
                            "preventDuplicates": false,
                            "onclick": null,
                            "showDuration": "300",
                            "hideDuration": "1000",
                            "timeOut": "5000",
                            "extendedTimeOut": "1000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        };
                        toastr['warning'](data.msg);
                    }
                    $("#message_body").val("");//清空输入框
                },
                error: function(data){
                    $("#message_body").val("");
                }
            })
        }
    }
  $("#msgSendBtn").on('click', mes_send)
  $("#msgClear").on('click', function(){
    $("#message_body").val("");
  })
</script>

app/views/chats/_chatwindowbody.html.erb
<div class="nano has-scrollbar custom-scrollbar scrollbar-near-moon" style="height:400px">
  <div class="nano-content pad-all" tabindex="0" style="right: -17px;">
    <ul class="list-unstyled media-block">

      <%= sync partial: 'message_row', collection: Message.by_chat(@chat), refetch: true %>
<!--上面那一行-->
      <%#= sync_new partial: 'message_row', resource: Message.new, scope: @chat, refetch: true %>
      <%= sync_new partial: 'message_row', resource: Message.new, scope: @chat, refetch: true %>
    </ul>
  </div>
  <div class="nano-pane">
    <div class="nano-slider" style="height: 141px; transform: translate(0px, 0px);"></div>
  </div>
</div> 

app/views/chats/_friendlist.html.erb
<% @friends.each do |user| %>
<li>
  <a class="collapsible-header waves-effect arrow-r py-2" style="height: 50px; font-size: 1rem; background-color: rgb(0,0,0,.2));">
    <i class="fa fa-user" style="font-size: 1rem;"></i> 
    <b><%= user.name %></b>
    <i class="fa fa-angle-down rotate-icon" style="font-size: 1.3rem;"></i>
  </a>
  <div class="collapsible-body">

    <div class="card testimonial-card">
      <div class="card-up " style="background-color: rgb(0,0,0,.2));">
      </div>

      <div class="avatar mx-auto white">

        <% if user.picture? %>
          <%= image_tag user.picture.url, class: "rounded-circle img-fluid", style: "height:110px;width:110px", alt: "avatar mx-auto white" %>
        <% else %>
           <%= image_tag "user-icon.png", class: "rounded-circle img-fluid", style: "height:110px;width:110px", alt: "avatar mx-auto white" %>
        <% end %>
        <!-- <img src="img/head.jpg" alt="avatar mx-auto white" class="rounded-circle img-fluid"> -->
      </div>

      <div class="card-body text-muted">
        <h4 class="card-title mt-1"><%= user.name %></h4>
        <hr>
        <p><i class="fa fa-quote-left"></i><%= user.essay %></p>
        <hr>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group ml-4 pl-2" role="group" aria-label="First group">

            <a href="/articles/<%= user.id %>" class="pl-0">
              <button type="button" class="btn btn-default cyan lighten-2">动态
              </button>
            </a>
            <%= form_for Chat.new, url: chats_path, method: :post do |f| %>
            <%= hidden_field_tag :users, [user.id] %>
            <%= button_tag(:class => "btn btn-default blue lighten-2") do %>
            聊天
            <% end %>
            <% end %>
            <%= link_to friendship_path(user), method: :delete, class: "p-0"  do %>
            <button type="button" class="btn indigo lighten-2 btn-default ">删除</button>
            <% end %>
            <!-- <button type="button" class="btn btn-lg cyan lighten-2">Info</button> -->
            <!-- <button type="button" class="btn btn-lg blue lighten-2">Chat</button> -->
            <!-- <button type="button" class="btn btn-lg indigo lighten-2">Delete</button> -->
          </div>
        </div>

      </div>

    </div>

  </div>
</li>
<% end %>