config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get :index_json
    end
  end

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'
  get 'sessions/logout' => 'sessions#destroy'

  get 'chatroom/' => 'chats#chatroom'
  post 'sendtorobot/' => 'messages#sendtorobot'
  post 'createarticle/' => 'articles#create'
  resources :articles, :only => [:destroy, :show]
  resources :footsteps, :only => [:create]
  post 'updatelike/' => 'articles#update'
  get 'developlog/' => 'developlog#index'

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    protect_from_forgery with: :exception
	include SessionsHelper
  def home
  	redirect_to chats_path if logged_in?
    #redirect_to chats_path
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_header.html.erb
    <header>
        <nav class="navbar navbar-light" style="background-color:rgb(0, 0, 0, 0.3);">
          <span class="navbar-text white-text">
          	<b>WMI CHAT ——你的轻量级在线聊天室</b>  
          </span>

	  <ul class="nav navbar-nav nav-flex-icons ml-auto">
			<li class="nav-item px-3">
	    	<%= link_to developlog_path, class: "nav-link waves-effect waves-light" do %>
	    		<i class="fa fa-address-card"></i> <span class="clearfix d-none d-sm-inline-block">用户指南</span>
	    	<% end %>
			</li>
	  </ul>
        </nav>
    </header>

app/views/homes/_login.html.erb
<%= form_for(:session, url: sessions_login_path, method: :post, html: {role: 'form'}) do |f| %>
<div class="modal-body mb-0">
  <div class="md-form form-sm">
    <i class="fa fa-address-card prefix",style="font-size:36px"></i>
    <%= f.label :email, "邮箱" %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="md-form form-sm">
    <i class="fa fa-key prefix",style="font-size:36px"></i>
    <%= f.label :password, "密码" %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="d-flex justify-content-around">
    <div>
      <!-- Remember me -->
      <div class="form-check p-0 ">
        <input type="checkbox" class="form-check-input" id="materialLoginFormRemember">
        <label class="form-check-label" for="materialLoginFormRemember"><%= f.check_box :remember_me %>下次自动登录</label>
      </div>
    </div>
  </div>
  <div class="text-center mt-1-half my-4">
    <%= button_tag(type: "submit", class: "btn green mb-2 waves-effect waves-light ") do %>
    Sign in <i class="fa fa-home ml-1"></i>
    <% end %>
  </div>
  <p class="text-center">
    <%= link_to new_user_path do %>
    <!-- <a href="/users/new"> -->
      注册
    <!-- </a> -->
    <% end %>
    |
    <a href="">忘记密码</a>
  </p>

</div>

<% end %>

app/views/homes/home.html.erb
<body class="light-green-skin" aria-busy="true">
  <%= render 'homes/header' %>
  <main>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="modal-dialog cascading-modal" role="document">
            <div class="modal-content rounded " style="background-color: rgb(255, 255, 255,.8);">
              <div class="rounded " style="background-color: rgb(46, 139, 87,.8);"> 
                <h4 style="color: white; font-size: 16px; font-family: cursive; font-style: italic; letter-spacing: 6px; text-align: center;"> Nothing is true <br/> everything is permitted.</h4>
              </div>
              <%= render 'homes/login' %>
            </div>
          </div>
        </div>
        <div class="col-md-3"></div>
      </div>
    </div>
  </main>
  <%= render 'layouts/footer' %>
</body>