config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get :index_json
    end
  end

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'
  get 'sessions/logout' => 'sessions#destroy'

  get 'chatroom/' => 'chats#chatroom'
  post 'sendtorobot/' => 'messages#sendtorobot'
  post 'createarticle/' => 'articles#create'
  resources :articles, :only => [:destroy, :show]
  resources :footsteps, :only => [:create]
  post 'updatelike/' => 'articles#update'
  get 'developlog/' => 'developlog#index'

end

app/models/footstep.rb
class Footstep < ApplicationRecord
  belongs_to :user
  belongs_to :footstepuser, :class_name => "User"
end

app/controllers/footsteps_controller.rb
class FootstepsController < ApplicationController
  include SessionsHelper
  include ChatsHelper
	def create
		if params[:post][:body] == ""
			redirect_to article_path(params[:user_id]), flash: {"error": "还没有留下足迹"}
			return
		end
		footst = Footstep.new(user_id: params[:user_id], content: params[:post][:body], footstepuser_id: params[:footstepuser_id])
		if footst.save
			redirect_to article_path(params[:user_id]), flash: {"success": "足迹成功留下"}
		else
			redirect_to article_path(params[:user_id]), flash: {"error": "留下足迹失败"}
		end
	end
end

app/helpers/footsteps_helper.rb
module FootstepsHelper
end

app/views/footsteps/_newfootstep.html.erb
<div class="card card-cascade narrower mt-5" id="footstepinput" style="background-color: rgb(0,0,0,.4);">
  <div class="view view-cascade gradient-card-header lighten-2 narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center" style="background-color: #A52A2A">
    <a href="" class="white-text mx-3">给Ta留言</a>
    <div>
      <a href="/articles/<%= @userinfo.id %>/#footstepinput" type="button" class="btn btn-secondary py-2 px-4">重新编辑</a>
    </div>
  </div>

  <div class="px-4 pb-5">
    <%= form_for @newfootstep, url: footsteps_path, method: :post do |f| %>
    <div class="row pr-4">
      <div class="col-md-12">
        <div class="md-form mb-4 pink-textarea active-pink-textarea-2">
          <i class="fa fa-angle-double-right prefix" style="color:rgb(211,211,211,.6);"></i>
          <label for="post_body">在留言板上写下...</label>
          <%= hidden_field_tag :footstepuser_id, current_user.id %>
          <%= hidden_field_tag :user_id, @userinfo.id %>
          <%= text_area "post", "body", "class"=>"md-textarea form-control", "rows" => 3 %>
        </div>
      </div>
    </div>
    <div class="row pr-4">
      <div class="col-md-12 text-right">
        <%= f.submit '提交留言', class: 'btn btn-warning lighten-2 btn-sm' %>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/footsteps/_showfootstep.html.erb
<div class="card card-cascade narrower mt-5" id="footstepshowpanel" style="background-color: rgb(0,0,0,.4);">
  <div class="view view-cascade gradient-card-header narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center" style="background-color: rgb(47, 79, 79);">
    <a href="" class="white-text mx-3">Ta的留言板</a>
    <div>
      <% if @userinfo.id == current_user.id %>
      <a href="/chats/#footstepshowpanel" class="btn btn-secondary py-2 px-4" type="button">更新</a>
      <% else %>
      <a href="/articles/<%= @userinfo.id %>/#footstepshowpanel" class="btn btn-secondary py-2 px-4" type="button">更新</a>
      <% end %>
    </div>
  </div>

  <div class="p-4 pb-5">
    <% if @footstepall.count == 0 %>
      <p class="px-4 card-text text-center text-muted">
        快来第一个给Ta留言吧
      </p>
    <% end %>
    <% @footstepall.each do |footstep| %>
      <hr class="my-0">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <a href="/articles/<%= footstep.footstepuser.id %>">

        <% if footstep.footstepuser.picture? %>
          <%= image_tag footstep.footstepuser.picture.url, class: "img-sm" %>
        <% else %>
           <%= image_tag "user-icon.png", class: "img-sm" %>
        <% end %>

            </a>
          </div>
          <div class="col-md-8 pl-0">
            <h5 class="card-title text-muted">
              <%= footstep.footstepuser.name %>
            </h5>
              <%= %>
            <p class="card-text">
              于<%= footstep.created_at.to_s %>&nbsp;&nbsp;给Ta留言道:
            </p>
          </div>
        </div>
        <p class="card-text mt-2">
          <%= footstep.content %>
        </p>
      </div>
    <% end %>
  </div>

</div>